version: "3"
services:
  app:
    image: theguardianwolf/meteor-dev:latest
    command: /bin/bash -c "cd .. && git clone https://TheGuardianWolf:af592c7f1676514589eae23aedbf9c537f0d8fb5@github.com/TheGuardianWolf/flowboard && cd flowboard && meteor"
    stdin_open: true
    tty: true
    working_dir: /home/meteor/flowboard
    environment:
      LC_ALL: "C.UTF-8"
      MONGO_URL: "mongodb://db:27017/"
    ports:
      - "3000:3000"
    links:
      - db
  db:
    expose:
      - "27017"
    image: mongo
