version: "3"
services:
  app:
    image: theguardianwolf/meteor-dev:latest
    command: /bin/bash -c "sudo chown meteor -R flowboard && git clone https://{GIT_USERNAME}:${GIT_PAT_FLOWBOARD}@github.com/TheGuardianWolf/flowboard || cd /home/meteor/flowboard/flowboard && meteor npm install && meteor"
    stdin_open: true
    tty: true
    working_dir: /home/meteor
    environment:
      LC_ALL: "C.UTF-8"
      MONGO_URL: "mongodb://db:27017/"
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - "/home/meteor/flowboard"
  db:
    expose:
      - "27017"
    image: mongo
    volumes:
      - "/data/db"
