// Generated by typings
// Source: https://raw.githubusercontent.com/meteor-typings/blaze-layout/a28fe1542f67c4fdcebbba612c7e722f08973b59/main.d.ts
interface BlazeLayoutStatic {
  render(routeName: string, subTemplates?: { [templateName: string]: string; }): void;
  setRoot(rootSelectorDOMNodeOrJQueryObject: string | HTMLElement | Object): string; // TODO: fix JQuery Object def
}

declare var BlazeLayout: BlazeLayoutStatic;

declare module 'meteor/kadira:blaze-layout' {
  export var BlazeLayout: BlazeLayoutStatic;
}
